version: '2'

services:
  mysql:
    image: mysql:5.7.28
    container_name: mysql_test
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: node_mysql_ts
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ~/docker/test_db/mysql/data:/var/lib/mysql
